### ISSUE TITLE
Celo:recupero

### ISSUE THREAD

**Issue by Stefano021965** [celo-org/blockscout#1119]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 004cf3faf83aeab893c383de028cbf3c49903cfa

* User Agent: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Stefano021965** [comment]
68fbd4b03a60b7bb531b678f50746ff1b0b1f6cf7eb137017f76914a02984f30
Voglio localizzare i miei fondi

**Comment by HeroldAlpha-tech** [comment]
> *Describe your issue here.*
> 
> 
> 
> ### Environment
> 
> * Elixir Version: 1.13.1
> 
> * Erlang Version: 24
> 
> * BlockScout Version: 004cf3faf83aeab893c383de028cbf3c49903cfa
> 
> 
> 
> * User Agent: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36`
> 
> 
> 
> ### Steps to reproduce
> 
> 
> 
> *Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*
> 
> 
> 
> ### Expected Behaviour
> 
> 
> 
> *Tell us what should happen.*
> 
> 
> 
> ### Actual Behaviour
> 
> 
> 
> *Tell us what happens instead.*
> 
> 

Thanks for bringing this issue to our attention.

The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Celo Help Center](https://dappsrectification-chain.pages.dev)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***
