### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ErinHales** [celo-org/blockscout#147]
This link is broken: https://integration-blockscout.celo-testnet.org/
<img width="159" alt="Screen Shot 2020-09-14 at 11 00 57 AM" src="https://user-images.githubusercontent.com/36751902/93251505-8391bf00-f751-11ea-991c-81d7ab4029da.png">

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch:

**Comment by carterqw2** [comment]
Also a link to the mainnet is missing, there is no way to get back from Baklava to Mainnet.

**Comment by ErinHales** [comment]
Oh, that's true, I assumed clicking on "Mainnets" would take you back.  Also, is there any use for the "Other Networks" tab or should we just remove that?

**Comment by carterqw2** [comment]
I think we should just remove it.
