### ISSUE TITLE
Incorrect token balances

### ISSUE THREAD

**Issue by carterqw2** [celo-org/blockscout#177]
I’m not sure how the block explorer gets / caches balances but for some reason its showing a balance of 10 cUSD for this address when the Token Transfers clearly show that 10 cUSD came in and 9.99 went out: https://alfajores-blockscout.celo-testnet.org/address/0x4ca54eea6994d276168cd249f72d659e7171ce5a/token_transfers
Seems like a bug to us :slightly_smiling_face:

**Comment by jbsibille** [comment]
This could have been caused by our DB throttling issue
