### ISSUE TITLE
Delayin Token Transfer

### ISSUE THREAD

**Issue by Trustideji** [celo-org/blockscout#187]
*I transferred 20.51 Celos from Coinlist (0x4c6226a025372f90ccdec31c0abc7f957af5ce25) to Binance (0xfd9f4ec9a420aa7150d42cd5ee891662db39b566). Its more than an hour and the transaction is still pending. 
Please kindly help...

**Comment by carterqw2** [comment]
@Trustideji I can't see it in the list of pending transactions, could you provide more info and reopen if it's not resolved yet?
