### ISSUE TITLE
Update Privacy Consent Banner 

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/blockscout#194]
Update the language of the banner and the background color for accessibility 

### Environment
all

### Steps to reproduce
Go to website in incognito mode

### Expected behaviour

COPY: `Allow tracking of my activity on explorer.celo.org to help improve this website.
Understand more in our Privacy Policy[celo.org/privacy].

https://www.figma.com/file/E7HhqLi5TrFwcCpKriqEu4/Celo-Website-5.0?node-id=51%3A46&viewport=340%2C1652%2C0.40806612372398376

![Screen Shot 2021-02-12 at 9 21 43 AM](https://user-images.githubusercontent.com/3814795/107800579-c90fe380-6d13-11eb-94a6-3e54828f28db.png)
![Screen Shot 2021-02-12 at 9 21 56 AM](https://user-images.githubusercontent.com/3814795/107800583-ca411080-6d13-11eb-9230-a0965b436cfe.png)

### Actual behaviour

the current version has a low contrast ratio

**Comment by ErinHales** [comment]
#207
