### ISSUE TITLE
Investigate changes needed for Blockscout to support optional 3 extra transaction fields

### ISSUE THREAD

**Issue by carterqw2** [celo-org/blockscout#199]
Blockchain is investigating making Celo's 3 extra transaction fields optional.
We should have a sense of how much work needs to be done and the touchpoints for ensuring Blockscout doesn't break for transactions not including these fields.

https://www.notion.so/clabsco/Support-Ethereum-compatible-Transactions-5a30e946d0344e2cb3d1bc1677729a27

**Comment by mrsmkl** [comment]
It doesn't look like there are changes that are visible to blockscout. The RPC will just return null for the optional fields as before.
Anyway, tested locally, made a tx with metamask, and everything is working fine...

**Comment by carterqw2** [comment]
Thanks, @mrsmkl!
