### ISSUE TITLE
Integrate Sourcify with Blockscout

### ISSUE THREAD

**Issue by carterqw2** [celo-org/blockscout#209]

**Comment by aaronmboyd** [comment]
Current status is that I've got it working by merging in the single feature from the blockscout branch. Have tested locally on a contract that I built and deployed myself so I had the exact metadata and JSON.

@carterqw2 Awaiting instructions on licensing agreements and whether I can commit anywhere.

**Comment by aaronmboyd** [comment]
![Screenshot from 2021-04-06 10-40-11](https://user-images.githubusercontent.com/13218496/113851750-1c466580-979c-11eb-9e91-6f50e4165b8e.png)
![Screenshot from 2021-04-06 13-15-04](https://user-images.githubusercontent.com/13218496/113851754-1cdefc00-979c-11eb-950d-3ec4080cd209.png)
![Screenshot from 2021-04-06 13-20-55](https://user-images.githubusercontent.com/13218496/113851755-1d779280-979c-11eb-9b1e-c333a5d8eeb3.png)
![Screenshot from 2021-04-06 13-21-56](https://user-images.githubusercontent.com/13218496/113851757-1d779280-979c-11eb-9e88-f4e21c7af35d.png)
![image (1)](https://user-images.githubusercontent.com/13218496/113851850-37b17080-979c-11eb-807f-d821f8ddb6fc.png)

**Comment by carterqw2** [comment]
Great, @aaronmboyd! Confirmed with the team that it's okay to push the branch to our repo and merge like we usually do, so please proceed.

**Comment by aaronmboyd** [comment]
@mrsmkl @carterqw2 OK I've brought this up to date with master and pushed to `aaronmboyd/sourcify`. How do I test this? I see there's a test suite but I'm not sure how to add new pages to it, whether it's a snapshot style or functional testing etc.
