### ISSUE TITLE
Long Lock Wait times for the request

### ISSUE THREAD

**Issue by carterqw2** [celo-org/blockscout#213]
**Description**
Under load with a big number of transactions in blocks, the following query takes increasingly long time to complete:
```
INSERT INTO
  "tokens" AS t0 ("contract_address_hash",
    "holder_count",
    "inserted_at",
    "type",
    "updated_at")
VALUES
  ($1,$2,$3,$4,$5)
ON
  CONFLICT ("contract_address_hash") DO
UPDATE
SET
  "name" = EXCLUDED.name,
  "symbol" = EXCLUDED.symbol,
  "total_supply" = EXCLUDED.total_supply,
  "decimals" = EXCLUDED.decimals,
  "type" = EXCLUDED.type,
  "cataloged" = EXCLUDED.cataloged,
  "inserted_at" = LEAST(t0."inserted_at", EXCLUDED.inserted_at),
  "updated_at" = GREATEST(t0."updated_at", EXCLUDED.updated_at)
WHERE
  ((EXCLUDED.name,
      EXCLUDED.symbol,
      EXCLUDED.total_supply,
      EXCLUDED.decimals,
      EXCLUDED.type,
      EXCLUDED.cataloged) IS DISTINCT
  FROM (t0."name",
      t0."symbol",
      t0."total_supply",
      t0."decimals",
      t0."type",
      t0."cataloged")
    AND ( EXCLUDED.cataloged
      OR NOT t0."cataloged" )) RETURNING "updated_at",
  "inserted_at",
  "contract_address_hash",
  "holder_count",
  "cataloged",
  "type",
  "decimals",
  "total_supply",
  "symbol",
  "name"
```

The code that calls it is here https://github.com/celo-org/blockscout/blob/master/apps/explorer/lib/explorer/chain/import/runner/tokens.ex#L141

The tokens table has just 30 rows but the query is called up to 1000 times per hour. Usually, this call takes on average 7 seconds but under load it peaks up to 110 seconds.

![image.png](https://images.zenhubusercontent.com/5fb299ab87bffe6be1329686/9b41dc9b-e77f-4a47-a897-d3bca4cd9a09)

Very quickly this request hogs up all database connections and the indexer starts dropping tasks from the queue that results in a bunch of errors in the logs:
```
"Task #PID<0.2485.14> started from Indexer.Fetcher.CeloValidatorHistory terminating
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 1634ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
    (db_connection) lib/db_connection.ex:836: DBConnection.transaction/3
    (ecto) lib/ecto/repo/transaction.ex:15: Ecto.Repo.Transaction.transaction/4
    (stdlib) timer.erl:197: :timer.tc/3
    (explorer) lib/explorer/repo.ex:21: anonymous fn/2 in Explorer.Repo.logged_transaction/2
    (explorer) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
    (explorer) lib/explorer/chain/import.ex:319: anonymous fn/3 in Explorer.Chain.Import.import_transactions/2
    (elixir) lib/enum.ex:3325: Enumerable.List.reduce/3
    (elixir) lib/enum.ex:1998: Enum.reduce_while/3
    (explorer) lib/explorer/chain/import.ex:318: Explorer.Chain.Import.import_transactions/2
    (explorer) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
    (explorer) lib/explorer/chain/import.ex:128: Explorer.Chain.Import.all/1
    (indexer) lib/indexer/fetcher/celo_validator_history.ex:175: Indexer.Fetcher.CeloValidatorHistory.import_items/1
    (indexer) lib/indexer/fetcher/celo_validator_history.ex:56: Indexer.Fetcher.CeloValidatorHistory.run/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [%{block_number: 5098927, retries_count: 0}], callback_module: Indexer.Fetcher.CeloValidatorHistory, callback_module_state: {0, []}, metadata: []}]"
```

We modified the query as it differs from the original query in the upstream repo https://github.com/poanetwork/blockscout/blob/master/apps/explorer/lib/explorer/chain/import/runner/tokens.ex#L141, we added an additional condition to the `ON CONFLICT` clause.

I checked with Victor, they have never observed this behavior.

**Comment by aaronmboyd** [comment]
I don't understand how `AND ( EXCLUDED.cataloged OR NOT ? )` does anything and why it needs to be added to the conflict where clause.

The DISTINCT FROM already includes the `cataloged` column comparison, and they should be comparable as booleans?

Perhaps the query plan performs the IS DISTINCT FROM in a optimized way, and then outside of that, has to now perform another comparison using an unindexed column? 

Whenever I see DISTINCT in SQL it triggers my code smells sense. I know this implementation is in the original POA code, but why are we only updating if there is the data is different? The cost of skipping an update by performing a distinct could be higher than just simply updating and overwriting the old data (and incrementing the updated_date) every time on conflict.

**Comment by carterqw2** [comment]
Yeah, me neither, I only found this https://github.com/celo-org/blockscout/commit/44a1d9d984787b306e728f6c64f80c3d44a7b490#diff-c6403504c56b349856184854dc726fbdefc52038e96fa7872c56dc399914d3ab and https://github.com/celo-org/blockscout/commit/2acee0c49175ab4d8d00e17e6ebe61bf1488e7c0#diff-c6403504c56b349856184854dc726fbdefc52038e96fa7872c56dc399914d3abL161 but there is no much context. Maybe @mrsmkl remembers?

**Comment by mrsmkl** [comment]
I think this problem comes from the handling of CELO token. The problem was that the token must exist in the table before the transfers can be stored. It probably creates an empty token for each transaction, and doesn't filter them. I think we should just have a script to add the token to the DB when we initialize it, and remove the code that keeps making sure it exists.

**Comment by aaronmboyd** [comment]
OK perfect, might as well add CELO, cUSD, cEUR in the migration script
