### ISSUE TITLE
The Random smart contract doesn't return a the current random value when reading the contract

### ISSUE THREAD

**Issue by critesjosh** [celo-org/blockscout#228]
On the "Read Contract" tab of the Random contract ([link](https://explorer.celo.org/address/0x59f4ece373e26b39f389887c26b399497d7a4b68/read_contract)), the random value (#7) doesn't update, it seems to always return the same value.

```
7. random →
0x08c379a000000000000000000000000000000000000000000000000000000000
```

### Steps to reproduce

Go to [this](https://explorer.celo.org/address/0x59f4ece373e26b39f389887c26b399497d7a4b68/read_contract) page and read the value.

### Expected behaviour

The random value should update every block.

### Actual behaviour

The random value consistently returns 0x08c379a000000000000000000000000000000000000000000000000000000000.

**Comment by carterqw2** [comment]
The `RandomProxy` should be used instead as the contract itself doesn't have any of the storage needed. https://explorer.celo.org/address/0x22a4aaf42a50bfa7238182460e32f15859c93dfe/read_contract works.
