### ISSUE TITLE
Intermittent long request times

### ISSUE THREAD

**Issue by carterqw2** [celo-org/blockscout#258]
**Description**

Randomly it takes up to a minute to open transactions page:
![image.png](https://images.zenhubusercontent.com/5fb299ab87bffe6be1329686/3279557c-5258-4971-9b83-8e2c046e0f23)
![image.png](https://images.zenhubusercontent.com/5fb299ab87bffe6be1329686/ec98f778-f2f4-4487-9e0b-e3da8c9d45e2)
![image.png](https://images.zenhubusercontent.com/5fb299ab87bffe6be1329686/42485993-fea6-4c9d-b9ec-d5f3829c8fa9)

Nginx logs: https://cloudlogging.app.goo.gl/UnnWFmkAQxxZ1vWeA

![image.png](https://images.zenhubusercontent.com/5fb299ab87bffe6be1329686/fe40c30d-07d5-413c-9651-7babae72b50f)

Web app logs:
https://cloudlogging.app.goo.gl/W3oJbgt8LN8inW7C6

![image.png](https://images.zenhubusercontent.com/5fb299ab87bffe6be1329686/b453786a-326c-4125-a425-61d98fbb8da8)

DB logs:
![image.png](https://images.zenhubusercontent.com/5fb299ab87bffe6be1329686/bf1cd0d1-1f18-4055-b30a-b945161c3a61)

https://cloudlogging.app.goo.gl/Wu2iKtFpTaNaiGSH6

**Comment by carterqw2** [comment]
It sees that the slow materialized view refresh could cause it.

**Comment by rkachowski** [comment]
Production logs suggest the same, specifically refreshing the `celo_attestation_stats` materialized view.

```
10:35:42.891 [error] Postgrex.Protocol (#PID<0.657.0>) disconnected: ** (DBConnection.Co
nnectionError) client #PID<0.20276.6> timed out because it queued and checked out the co
nnection for longer than 60000ms

#PID<0.20276.6> was at location:

    :prim_inet.recv0/3
    (postgrex 0.15.8) lib/postgrex/protocol.ex:2838: Postgrex.Protocol.msg_recv/4
    (postgrex 0.15.8) lib/postgrex/protocol.ex:1880: Postgrex.Protocol.recv_bind/3
    (postgrex 0.15.8) lib/postgrex/protocol.ex:1735: Postgrex.Protocol.bind_execute_clos
e/4
    (db_connection 2.4.0) lib/db_connection/holder.ex:325: DBConnection.Holder.holder_ap
ply/4
    (db_connection 2.4.0) lib/db_connection.ex:1314: DBConnection.run_execute/5
    (db_connection 2.4.0) lib/db_connection.ex:1409: DBConnection.run/6
    (db_connection 2.4.0) lib/db_connection.ex:574: DBConnection.parsed_prepare_execute/
5

10:35:42.891 [error] GenServer Indexer.Block.Catchup.BoundIntervalSupervisor terminating

** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the poo
l, possibly due to a timeout or because the pool has been terminated)
    (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:749: Ecto.Adapters.SQL.raise_sql_call_erro
r/1
    (indexer 0.1.0) lib/indexer/block/catchup/bound_interval_supervisor.ex:237: Indexer.
Block.Catchup.BoundIntervalSupervisor.handle_info/2
    (stdlib 3.14.1) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.1) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

notable line being `(indexer 0.1.0) lib/indexer/block/catchup/bound_interval_supervisor.ex:237: Indexer.
Block.Catchup.BoundIntervalSupervisor.handle_info/2` -> https://github.com/celo-org/blockscout/blob/master/apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex#L237
