### ISSUE TITLE
Blockscout UI - Navigation

### ISSUE THREAD

**Issue by mattdkim** [celo-org/blockscout#454]
This ticket encompasses re-organizing navigation, including the "more" tab; [file here](https://docs.google.com/spreadsheets/d/1TzuraROU5SA43xwR9MtZA6VZHNYf4mVqvFWsZNkVX68/edit#gid=2145272375)
The list of dapps in "More" tab follow the list that are featured in [Valora](https://valoraapp.com/blog/new-dapps-new-ways-to-use-your-crypto)

![Screen Shot 2022-04-12 at 5.11.18 PM.png](https://images.zenhubusercontent.com/6147a23f6770dab153220bb6/62e96427-9f49-413c-8de4-48e406c3f667)

**Comment by eruizgar91** [comment]
Nav cleanup and token page cleanup are still pending
