### ISSUE TITLE
Celo Balance not displaying on explorer

### ISSUE THREAD

**Issue by mattdkim** [celo-org/blockscout#473]

**Comment by mattdkim** [comment]
![Image from iOS.jpg](https://images.zenhubusercontent.com/6147a23f6770dab153220bb6/de9e2e95-a0d2-41e0-825a-d2e89db98806)Alex from Foundation reported this bug:

"Hi @Matt, Is there a bug with the explorer maybe? Data for this address isn't pulling into the spreadsheet (https://explorer.celo.org/address/0x64947cDB38d9d364eD5Ab78bfa23b29DE2ecdF7b/transactions), I can, however, see the following balance with the CLI: 6.63303199451611780784635e+23"

**Comment by mattdkim** [comment]
@eruizgar91 could you take a look at this when you get a chance?

**Comment by eruizgar91** [comment]
It seems that the address doesn't have the value in the table `address_coin_balances` updated. I will check if this is happening for more addresses
