### ISSUE TITLE
Add Celo Stats Page on Explorer

### ISSUE THREAD

**Issue by mattdkim** [celo-org/blockscout#508]
**Context**
As a part of Data Accessibility initiative to utilize Data Studio, this ticket aims to add a Celo Stats page on explorer that links to a public dashboard built in Data Studio. This first iteration will include the followings:

- Transactions: Daily, Monthly
- Addresses: Daily Active, Monthly Active, Accumulative
- Gas: % used Daily, % used Monthly
- Transaction Fees: Daily Total, Monthly Total

**Notes**
- Further instructions and design [here](https://www.figma.com/file/SJM6zI1XUvRZisxsTvj40T/explorer-analytics-v1.0)
- Please add data@clabs.co as a owner of the dashboard
- This dash will go through future iterations to include more insights e.g. transactions by apps, breakdown of addresses by balances

**Comment by eruizgar91** [comment]
https://datastudio.google.com/u/0/reporting/e0a253b1-fa37-43d0-bbc3-2706a64f2211/page/hDehC/edit

**Comment by mattdkim** [comment]
@eruizgar91 

Can we change the default timeframe to previous 365 days (go to advanced in the menu)? I can't save the change b/c I'm blocked on logging in via data@clabs.co.

Also the legends for all charts has to follow the copy from the design e.g. "average gas used per day".

The first chart in the 3rd row (gas) seems weird - thoughts?

**Comment by mattdkim** [comment]
Hi @eruizgar91 , the timeframe selector seems to be gone - could we add that back?

**Comment by mattdkim** [comment]
We should hold off on releasing this until we figure out why there are discrepancies between this dashboard vs Celo Explorer; if it is DB updating issues, we need to include the latest update time, similar to this:  ![Screen Shot 2022-01-16 at 4.47.15 PM.png](https://images.zenhubusercontent.com/6147a23f6770dab153220bb6/6a3f1eae-c181-4f6f-afa3-b294e55ea442)
