### ISSUE TITLE
CSV Download - error with amount 

### ISSUE THREAD

**Issue by mattdkim** [celo-org/blockscout#520]
The downloaded CSV file for both transfer and transaction have wrong value for the amount (col H for txt, col I for transfer). It seems like the value is being multiplied by 10e8.

![Screen Shot 2022-01-08 at 12.54.30 AM.png](https://images.zenhubusercontent.com/6147a23f6770dab153220bb6/9e44e19b-e788-4254-964a-960bac37084b) ![Screen Shot 2022-01-08 at 12.53.26 AM.png](https://images.zenhubusercontent.com/6147a23f6770dab153220bb6/a91d6743-9c0f-4b16-b3ce-83ca63416bbe)

**Comment by carterqw2** [comment]
@mattdkim that's kind of expected as values are in Weis. You can use an [online converter](https://eth-converter.com/), put the desired value into the `Ether` column and check if the `Weis` column matches the one you see in the CSV.

**Comment by mattdkim** [comment]
I see - could we put change the copy to TokenTransferred(weis) TransactionFee(weis), and add two additional columns that has the values in USD - TokenTransferred(USD) TransactionFee(USD)? We'd need to do for both downloads as it'd be unclear/confusing for the users with limited knowledge in blockchain.
