### ISSUE TITLE
Investigate Sourcify Issues

### ISSUE THREAD

**Issue by mattdkim** [celo-org/blockscout#529]
Data on verification status of Celo smart contracts on Sourcify is lost after some time and is not longer accessible. Need to investigate why:
- Reachout to Sourcify
- Find/implement a better pipeline
- Possible host an IPFS node

**Comment by eruizgar91** [comment]
They don't have planned to enable monitoring ipfs for celo networks after talk with them. It should be working after the fix of the issue https://github.com/celo-org/celo-monorepo/issues/9182. IMO the current script is the better solution for the deployment of the contracts.
