### ISSUE TITLE
API - mislabeled data

### ISSUE THREAD

**Issue by mattdkim** [celo-org/blockscout#539]
Sihan from Celo Tax here, We were looking through a wallet 0x7FF0126dD0cA567fD32a2b06Ce925072a6d2F79c
and found out that the Celo Explorer API is labeling the token name differently than the explorer front end. The front end is showing that the token exchanged in this transaction are cUSD and cUSDC, but the API is showing "Mobius cUSD/bUSDC LP"
The transaction hash is: 0xb4544d6b1cdc21fd8e03732ba690ace28b7dd2a736fee31bdcda6adc1efb0fba

Here are the URLs to the API and the frontend.
FrontEnd: https://explorer.celo.org/tx/0xb4544d6b1cdc21fd8e03732ba690ace28b7dd2a736fee31bdcda6adc1efb0fba/token-transfers
API: https://explorer.celo.org/api/?module=account&action=tokentx&address=0x7FF0126dD0cA567fD32a2b06Ce925072a6d2F79c

I have also attached the screenshots from the frontend and API results with the mail.

![Screenshot_2022-01-28_23-10-10.png](https://images.zenhubusercontent.com/6147a23f6770dab153220bb6/bfa28421-f909-427d-9986-5c1792c64175)![unknown.png](https://images.zenhubusercontent.com/6147a23f6770dab153220bb6/e075115d-ec31-4447-b212-7c8f9a85877a)

**Comment by carterqw2** [comment]
Previously, the account 0x7ff0126dd0ca567fd32a2b06ce925072a6d2f79c locked some amount of cUSD and cUSDC tokens (token pair) in a liquidity pool and got some amount of the LP (liquidity provider) token in exchange to get rewards for providing liquidity for this token pair.

In this transaction, the account performed the opposite operation - they removed liquidity from the pool, they returned (or "burned") some amount of the LP token and got some amount of the other two tokens back.
So, there are three token transfers involved in this transaction.

In the UI it can be found here:
![image.png](https://images.zenhubusercontent.com/5fb299ab87bffe6be1329686/490dd0a3-86e8-4d1b-b971-8773cc41e4a5)

In the [API response](https://explorer.celo.org/api/?module=account&action=tokentx&address=0x7FF0126dD0cA567fD32a2b06Ce925072a6d2F79c) that would correspond to three independent token transfers as well:
![image.png](https://images.zenhubusercontent.com/5fb299ab87bffe6be1329686/5db33236-8444-4645-9163-e49b8947e28a)

All three are in place with correct token names and symbols.
