### ISSUE TITLE
Investigate 'missing' incoming cUSD 

### ISSUE THREAD

**Issue by mattdkim** [celo-org/blockscout#540]
**Submitted by**: Celo Tax

**Problem:** This address has an outgoing cUSD transfer here, but doesn't have any incoming cUSD in its list of token transfer

**Definition of done**: comment on this ticket if this is an expected behavior and why. If not, then continue with the fix, update the estimate, comment below on what the root cause was.

**Resources**
address: 0x4cb665c9dfd45a59f55c458f00cb2e4f53256163
https://explorer.celo.org/address/0x4CB665C9DFD45A59f55C458f00Cb2E4F53256163/token-transfers

**Comment by eruizgar91** [comment]
First thing I noticed is that there are 13 token transfers and there are only 9 in the list, and it's not posible to click in the pages

**Comment by eruizgar91** [comment]
![image.png](https://images.zenhubusercontent.com/5f046daf3f7f99fca8cf21a5/cba9260f-cb77-48e7-8fa3-abfb5c8d1ea4)

As it's possible to see, there are some transactions without transaction hash, that are the ones that are not being showed in the list. I checked and the values match.

**Comment by mattdkim** [comment]
closing this ticket as the epoch transaction UI work will cover this
