### ISSUE TITLE
Add endpoints for rewards and document

### ISSUE THREAD

**Issue by mattdkim** [celo-org/blockscout#542]
https://github.com/celo-org/blockscout/pull/537

- fix 4 tests and credo failing

- add endpoint that gets voter rewards for all groups
- add endpoints for validator group rewards and validator rewards
- API documentation, Tables and Schema documentation (Refer/ Add to here: https://www.notion.so/clabsco/Blockscout-DB-Schema-f6f044a7b7714fd7991709021e2af22a)
- Document the calculations, tests, new process

**Comment by carterqw2** [comment]
Part of two other PRs, should be done there.
