### ISSUE TITLE
Technical Doc: Sourcify Autodeploy script

### ISSUE THREAD

**Issue by mattdkim** [celo-org/blockscout#547]
Document the detail re: Script that autodeploys files to Sourcify 

Include but not limited to:
- What it does
- How it works 
- System diagram
- Repo

Document here: https://www.notion.so/clabsco/Celo-Contract-Verification-Autodeploy-Script-ac770b5aac614c1ebeda7978217ec64a

**Comment by eruizgar91** [comment]
Document updated https://www.notion.so/clabsco/Celo-Contract-Verification-Autodeploy-Script-ac770b5aac614c1ebeda7978217ec64a
