### ISSUE TITLE
Celo: <Dollar not showing>

### ISSUE THREAD

**Issue by Nikhilnknk** [celo-org/blockscout#906]
I transferred my celo from binance to celo metamask but its not showing in metamask celo
and i opened celo in block explorer where my money was shown out . i dont know what that mean. also my money was automaticallly transferred to another adddress
![Transaction history - Wallet - Binance - Google Chrome 27-05-2023 12_35_59](https://github.com/celo-org/blockscout/assets/134768475/319f6f5f-960f-4e0c-9a49-56a01e937eb3)
![Transaction history - Wallet - Binance - Google Chrome 27-05-2023 11_54_48](https://github.com/celo-org/blockscout/assets/134768475/392cbcf0-bcb9-438f-a35c-08db9673b056)

**Comment by carterqw2** [comment]
Hi @Nikhilnknk, I can see that with the [first TX](https://explorer.celo.org/mainnet/tx/0x23b19b54a614cbd2ba1f69a08d2c37b8bd4e92b3c8510dc66a0b2bdfc3bf600a) you received 2.56034913 CELO.
Regarding the [second TX](https://explorer.celo.org/mainnet/tx/0xcad9258267047d9918494b0903b6b2a8b44908965081a41448ba60041d447a47) that you probably refer to when you say "my money was automaticallly transferred to another adddress", it's impossible for me to say who or what initiated the transfer. All I know that it payed a very high TX fee - $0.467 just to transfer $0.867 worth of CELO. Potentially, your wallet is compromised.
<img width="697" alt="image" src="https://github.com/celo-org/blockscout/assets/20768968/889b65bf-a3c7-46e8-8154-173b1847015a">
