### ISSUE TITLE
EOL reserve stats on explorer

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/blockscout#970]
## Context

Currently the [explorer stats](https://explorer.celo.org/mainnet/stats) include a "Mento reserves" tab:

<img width="1299" alt="image" src="https://github.com/celo-org/blockscout/assets/46296830/09c6b4af-f08c-420f-8515-e73a556fad0d">

The stats including the composition and total amount are incorrect (because they are out-of-date, the reverse is using new addresses to hold reserves). For example:

- Total reserve holdings:
  - explorer stats: $78,387,971
    <img width="250" alt="image" src="https://github.com/celo-org/blockscout/assets/46296830/4cdec859-0508-413f-8ef6-1ce021b7753b">
  - mento page: $111,465,849
    <img width="263" alt="image" src="https://github.com/celo-org/blockscout/assets/46296830/f86f558d-c912-46c8-8935-fd422a62911e">

The Mento team owns the official reserve website at [reserve.mento.org](https://reserve.mento.org/).
It's the most up-to-date page and is maintained by the Mento team. 
<img width="1214" alt="image" src="https://github.com/celo-org/blockscout/assets/46296830/3793ec59-5e54-470c-bb18-1a9b8332940e">

I propose we "end-of-life" the reserve stats tab, because it requires eng maintenance to keep it up-to-date and is misleading if it is out-of-date.

## Next steps

- [ ] Remove stats iframe and replace with deprecation message (I don't think we can easily add a banner for the stats page only). Message:
> "Looking for Mento reserve stats? You can find them at [reserve.mento.org](http://reserve.mento.org/)".

From Subha:
> You can do a 90 day notice, since we don't have any competing or higher priority notices for now.
I don't think we're able to add a banner for the stats page only (if I understand correctly, banners are global and shared across all page. They are currently set here: [[Public] Blockscout Banners Data](https://docs.google.com/spreadsheets/d/1EstTfplZ83nWIUHyx3vyA2g7JGLOT-rV5AQLXGrUrc0/edit#gid=1302560054))

After 90 days (~Wed, Dec 14):

- [ ] Remove reserve stats tab and deprecation notice entirely

**Comment by ssubram11** [comment]
I prefer a notice that the latest stats are at the official Mento page so it's not a jarring change. You can remove tab with an alert at the top of the page.

**Comment by 0xarthurxyz** [comment]
## QA

Testing feature in [staging environment](https://rc1staging-blockscout.celo-testnet.org/rc1staging/stats).
Works as expected:

- the iframe is remove
- the hovering over the tab shows a message linking to mento

https://github.com/celo-org/blockscout/assets/46296830/db4112d7-5c4a-4439-965b-b7247b9f8d54

**Comment by 0xarthurxyz** [comment]
QAd in [PR](https://github.com/celo-org/blockscout/pull/979#issuecomment-1768184861)
