### ISSUE TITLE
Update where the base fee is sent after gingerbread hardfork

### ISSUE THREAD

**Issue by shazarre** [celo-org/blockscout#984]
After gingerbread hardfork the base fee is no longer sent to community fund, but to fee handler instead. Currently explorer still displays `Community Fund` and should be `Fee Handler` for both [block](https://explorer.celo.org/mainnet/block/21992313/transactions) and [transaction](https://explorer.celo.org/mainnet/tx/0x1c0f947c9ae29d31e58b5ec96ed4f64bdbffa33ba830bd40652c48026c1b76ff) page. 

<img width="369" alt="Screenshot 2023-10-18 at 14 08 27" src="https://github.com/celo-org/blockscout/assets/312010/c15956b2-11f5-49a9-b526-acd53812ba9b">

[Gingerbread release](https://github.com/celo-org/celo-blockchain/releases/tag/v1.8.0)
[Gingerbread activation config](https://github.com/celo-org/celo-blockchain/blob/116243d718843b04beba9c6c094a25e0d50e2fa5/params/config.go#L69)
[Fee Handler on Explorer](https://explorer.celo.org/mainnet/address/0xcD437749E43A154C07F3553504c68fBfD56B8778)

**Comment by 0xarthurxyz** [comment]
Small note (for future reference), that the message when hoovering over the "i" needs to be updated too (e.g. [block](https://explorer.celo.org/mainnet/block/21992313/transactions))

<img width="488" alt="image" src="https://github.com/celo-org/blockscout/assets/46296830/03aa38a9-0a5d-4267-8389-0bba29c62f80">

**Comment by 0xarthurxyz** [comment]
Noting that this is low priority and Blockscout is feature frozen.
